# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xtreaming
email: dechcaudron@nohostyet.com
description: > # this means to ignore newlines until "baseurl:"
  Xtreaming is a free, open source client to stream music from your own server
  to your mobile device.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dechcaudron.github.io/xtreaming-app-android" # the base hostname & protocol for your site
twitter_username: hbaelx
github_username:  Dechcaudron

# Build settings
markdown: kramdown
